services:
  - type: web
    name: django-blog-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: "django-blog-app.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-blog-redis
          property: connectionString

  - type: redis
    name: django-blog-redis
    plan: free
    ipAllowList: []

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog_user
    plan: free
